### ISSUE TITLE
react-fusioncharts is incompatilble with TypeScript --noImplicitAny

### ISSUE THREAD

**Issue by mc-suchecki** [fusioncharts/fusioncharts-dist#10]
When I try to import react-fusioncharts in my React project written in TypeScript, the following error is present:

```
TypeScript error in (...)/node_modules/fusioncharts/index.d.ts(205,71):
Parameter 'output' implicitly has an 'any' type.  TS7006
```

This seems like a similar problem like [here](https://github.com/fusioncharts/angular-fusioncharts/issues/56#issue-419148055).

The workaround is to set `skipLibCheck` to true in tsconfig.json. However, this is not recommended by TypeScript authors [here](https://github.com/Microsoft/TypeScript/issues/18974#issuecomment-334875560).

Can we expect this to be fixed at some point in the future? Would you accept a PR fixing that?

**Comment by AyanBhadury** [comment]
Please upgrade to the latest version of the react-fusioncharts component, all the type definitions, and typescript support is added  - https://github.com/fusioncharts/react-fusioncharts-component
