### ISSUE TITLE
Pie chart does not have any labels when there is only one data element

### ISSUE THREAD

**Issue by erik881** [fusioncharts/fusioncharts-dist#2]
Currently if you have more than 1 data element for pie chart everything works good (it shows labels for each pie chart segment) but if there is only 1 element no labels are visible.

http://jsfiddle.net/erik88/2dmotkpb/ - labels exist
http://jsfiddle.net/erik88/2dmotkpb/1/ - labels do not exist

**Comment by AyanBhadury** [comment]
Hello,

Seems like the above links are broken, you could try out with the 3.16.0 build, here is a demo - http://jsfiddle.net/4a5sj8fz/
