### ISSUE TITLE
Div lines are overlapping the x-axis border line

### ISSUE THREAD

**Issue by StefanT123** [fusioncharts/fusioncharts-dist#5]
I can't set different color for the x-axis border line, because the div lines are overlapping the x-axis border line.

![image](https://user-images.githubusercontent.com/28436358/47781357-cbde9a00-dcfd-11e8-90dd-78f6820fd1be.png)

Here's the screenshot of my html:

![image](https://user-images.githubusercontent.com/28436358/47781571-4d362c80-dcfe-11e8-9c6e-909b0d16ec25.png)

NOTE: I'm using vue-fusioncharts, but I looked at the code and I saw that the vue-fusionchart is just a wrapper around fusioncharts.

**Comment by srishti-fc** [comment]
You may try providing a contrasting color for the xAxis Border Line or try increasing thickness of the  xAxis Border Line.
Reference sample: https://codesandbox.io/s/msline-lzbw4?file=/src/App.vue
