### ISSUE TITLE
Including fusioncharts to a create-react-app makes compilation time unbearably slow

### ISSUE THREAD

**Issue by gajus** [fusioncharts/fusioncharts-dist#6]
I have considered using FusionCharts in one our projects, but after trying it, was dissuaded because of the drastically increased compilation time.

Simply including `import FusionCharts from 'fusioncharts';` to a create-react-app project increases the compilation time from ~500ms to 5 seconds plus.

**Comment by soumyasdutta** [comment]
Hi,
Compilation time could depend on many factors primarily the code snippet written also like to let you know there was a known issue regarding compilation time for create-react-app (https://github.com/facebook/create-react-app/issues/5820) 

Still you could check the following simple sample and let us know whether you are getting any issue https://www.dropbox.com/s/xd4x8qhrikb3hop/demofusioncharts.zip?dl=0

**Comment by gajus** [comment]
Ended up switching to https://echarts.apache.org/examples/en/ long time ago.
